package se.spaced.server.trade;

public enum TradeActions {
	INITIATED,
	OFFER_UPDATED,
	INITIATOR_ACCEPT,
	COLLABORATOR_ACCEPT,
	INITIATOR_RETRACT,
	COLLABORATOR_RETRACT,
	INITIATOR_REJECTED,
	COLLABORATOR_REJECTED,
	ABORTED
}
