package se.spaced.client.ardor.ui.events;

public enum OnlineEvents {
	PLAYER_LOGGED_OUT,
	PLAYER_LOGGED_IN,
	LOGIN_FAILED,
	RECEIVED_SALTS,
	REQUIRES_AUTHENTICATOR_AUTHENTICATION,
	CHARSELECT_PLAYER_DATA_UPDATE
}
