package se.spaced.client.ardor.ui.events;

public enum TradeEvents {
	TRADE_INITIATED,
	TRADE_ITEM_ADDED,
	TRADE_NEGOTIATING,
	TRADE_FAILED_TO_ADD_ITEM, TRADE_CLOSED, TRADE_ABORTED, TRADE_ACCEPTED, TRADE_COMPLETED, TRADE_FAILED_TO_COMPLETE,
	TRADE_INIT_FAILED,
	MONEY_AWARDED,
	MONEY_SUBTRACTED
}
