package se.spaced.client.ardor.ui.events;

public enum VendorEvents {
	VENDOR_STOCK_ITEMS,
	VENDOR_CANNOT_AFFORD,
	VENDOR_ADDED_ITEM,
	VENDOR_OUT_OF_RANGE,
	VENDOR_DESPAWNED,
	VENDOR_INVENTORY_FULL,
	VENDOR_BOUGHT_ITEM
}
