package se.spaced.client.ardor.ui.events;

public enum ItemEvents {
	INVENTORY_ADD_ITEM,
	INVENTORY_REMOVE_ITEM,
	INVENTORY_UPDATED,
	EQUIPPED_ITEM,
	UNEQUIPPED_ITEM,
	EQUIP_ITEM_FAILED,
	UNEQUIP_ITEM_FAILED,
	RECEIVED_LOOT
}
